import { GoogleGenAI, Modality } from "@google/genai";
import type { ImageFile } from '../types';

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export const generatePoster = async (
  productImage: ImageFile,
  productName: string,
  slogan: string,
  style: string
): Promise<string> => {
  try {
    const prompt = `
      Transform the following product image into a professional, eye-catching advertisement poster with a "${style}" theme.

      Product Name: "${productName}"
      Slogan: "${slogan}"

      Instructions:
      1. Isolate the main product from the provided image.
      2. Create a background and setting that perfectly matches the "${style}" style. For example:
          - Minimalist: A clean, simple background with neutral colors and lots of negative space.
          - Vibrant: Bright, bold, and saturated colors with dynamic shapes.
          - Retro: Vintage color palettes, grainy textures, and classic typography from the 70s or 80s.
          - Elegant: Luxurious textures like marble or silk, sophisticated colors, and graceful fonts.
          - Futuristic: Neon glows, metallic surfaces, and sleek, high-tech graphic elements.
      3. Integrate the product name and slogan seamlessly into the poster design using stylish, modern, and legible typography that fits the "${style}" aesthetic.
      4. Enhance the overall image with professional lighting, color grading, and composition to create a premium look consistent with the chosen style.
      5. The final output must be a single, complete advertisement poster image. Do not include any explanatory text outside of the poster design itself.
    `;

    const imagePart = {
      inlineData: {
        data: productImage.base64,
        mimeType: productImage.mimeType,
      },
    };

    const textPart = {
      text: prompt,
    };

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [imagePart, textPart],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
      }
    }
    
    throw new Error("No image was generated by the API.");

  } catch (error) {
    console.error("Error generating poster:", error);
    throw new Error("Failed to generate poster. Please check the console for more details.");
  }
};